# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import machine_pb2 as machine__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in machine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MachineServiceStub(object):
    """Service definition for sending clock messages.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendClockMessage = channel.unary_unary(
                '/distributed.MachineService/SendClockMessage',
                request_serializer=machine__pb2.ClockMessage.SerializeToString,
                response_deserializer=machine__pb2.Ack.FromString,
                _registered_method=True)


class MachineServiceServicer(object):
    """Service definition for sending clock messages.
    """

    def SendClockMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MachineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendClockMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendClockMessage,
                    request_deserializer=machine__pb2.ClockMessage.FromString,
                    response_serializer=machine__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.MachineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.MachineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MachineService(object):
    """Service definition for sending clock messages.
    """

    @staticmethod
    def SendClockMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.MachineService/SendClockMessage',
            machine__pb2.ClockMessage.SerializeToString,
            machine__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
