# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machine.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'machine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmachine.proto\x12\x0b\x64istributed\"N\n\x0c\x43lockMessage\x12\x12\n\nmachine_id\x18\x01 \x01(\t\x12\x15\n\rlogical_clock\x18\x02 \x01(\x03\x12\x13\n\x0bsystem_time\x18\x03 \x01(\x03\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32Q\n\x0eMachineService\x12?\n\x10SendClockMessage\x12\x19.distributed.ClockMessage\x1a\x10.distributed.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'machine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOCKMESSAGE']._serialized_start=30
  _globals['_CLOCKMESSAGE']._serialized_end=108
  _globals['_ACK']._serialized_start=110
  _globals['_ACK']._serialized_end=132
  _globals['_MACHINESERVICE']._serialized_start=134
  _globals['_MACHINESERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
