# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'clock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63lock.proto\x12\x11\x64istributed_clock\"K\n\x0c\x43lockMessage\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x15\n\rlogical_clock\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"!\n\rClockResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\x62\n\x0c\x43lockService\x12R\n\x0bSendMessage\x12\x1f.distributed_clock.ClockMessage\x1a .distributed_clock.ClockResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOCKMESSAGE']._serialized_start=34
  _globals['_CLOCKMESSAGE']._serialized_end=109
  _globals['_CLOCKRESPONSE']._serialized_start=111
  _globals['_CLOCKRESPONSE']._serialized_end=144
  _globals['_CLOCKSERVICE']._serialized_start=146
  _globals['_CLOCKSERVICE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
